# Generated by Django 2.2.10 on 2021-01-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=30, null=True)),
                ('FirstName', models.CharField(max_length=30, null=True)),
                ('FullName', models.CharField(max_length=30, null=True)),
                ('Email', models.EmailField(max_length=30, null=True)),
                ('Age', models.CharField(max_length=2, null=True)),
                ('Phone', models.CharField(max_length=8, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Sexe', models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], max_length=30, null=True)),
                ('Country', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
