# Generated by Django 2.2.10 on 2021-01-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='FirstName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='FullName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='LastName',
        ),
    ]
