# Generated by Django 2.2.10 on 2021-01-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Image',
            field=models.ImageField(blank=True, default='preson.png', null=True, upload_to=''),
        ),
    ]
